
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador_Sintactico;

/** CUP generated class containing symbol constants. */
public class Token {
  /* terminals */
  public static final int TKN_PTO = 27;
  public static final int TKN_MENIGU = 32;
  public static final int TKN_CHAR = 21;
  public static final int TKN_SELECT = 4;
  public static final int TKN_WHERE = 6;
  public static final int TKN_CPAR = 25;
  public static final int TKN_IGUAL = 33;
  public static final int TKN_OR = 36;
  public static final int TKN_AVG = 16;
  public static final int TKN_MEN = 29;
  public static final int TKN_ID = 38;
  public static final int TKN_VARCHAR = 20;
  public static final int TKN_TODO = 11;
  public static final int TKN_APAR = 24;
  public static final int TKN_GROUP = 7;
  public static final int TKN_BY = 9;
  public static final int TKN_TABLE = 3;
  public static final int TKN_PTOCOMA = 26;
  public static final int TKN_SUM = 17;
  public static final int TKN_KEY = 13;
  public static final int TKN_MAY = 30;
  public static final int EOF = 0;
  public static final int TKN_MAX = 19;
  public static final int TKN_DIST = 34;
  public static final int TKN_CREATE = 2;
  public static final int error = 1;
  public static final int TKN_COMA = 28;
  public static final int TKN_STRING = 22;
  public static final int TKN_NULL = 14;
  public static final int TKN_ORDER = 8;
  public static final int TKN_FROM = 5;
  public static final int TKN_MAYIGU = 31;
  public static final int TKN_INT = 39;
  public static final int TKN_COUNT = 15;
  public static final int TKN_APOST = 37;
  public static final int TKN_PRIMARY = 12;
  public static final int TKN_AND = 35;
  public static final int TKN_NOT = 10;
  public static final int TKN_INTEG = 23;
  public static final int TKN_MIN = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TKN_CREATE",
  "TKN_TABLE",
  "TKN_SELECT",
  "TKN_FROM",
  "TKN_WHERE",
  "TKN_GROUP",
  "TKN_ORDER",
  "TKN_BY",
  "TKN_NOT",
  "TKN_TODO",
  "TKN_PRIMARY",
  "TKN_KEY",
  "TKN_NULL",
  "TKN_COUNT",
  "TKN_AVG",
  "TKN_SUM",
  "TKN_MIN",
  "TKN_MAX",
  "TKN_VARCHAR",
  "TKN_CHAR",
  "TKN_STRING",
  "TKN_INTEG",
  "TKN_APAR",
  "TKN_CPAR",
  "TKN_PTOCOMA",
  "TKN_PTO",
  "TKN_COMA",
  "TKN_MEN",
  "TKN_MAY",
  "TKN_MAYIGU",
  "TKN_MENIGU",
  "TKN_IGUAL",
  "TKN_DIST",
  "TKN_AND",
  "TKN_OR",
  "TKN_APOST",
  "TKN_ID",
  "TKN_INT"
  };
}

